### ISSUE TITLE
Support for Anki format files in the future?

### ISSUE THREAD

**Issue by wennerryle** [Cabidge/flashpack#2]
Anki has a large community that creates and shares flashcards every day, how about supporting APKG files?

https://ankiweb.net/shared/decks?search=english

It will be great

**Comment by Cabidge** [comment]
This is definitely something I've thought about, but until I stabilize the card pack format, I don't have any plans of doing so. Could be a good idea later down the line though.

**Comment by wennerryle** [comment]
Thank you for your reply!
